export const companies = {
  cnpj: 0,
  addresses: [
    {
      type: "",
      street: "",
      number: "",
      complement: "",
      neighborhood: "",
      city: "",
      district: "",
      postal_code: "",
      priority: 0,
    },
  ],
  age: "",
  branch_offices: [],
  business_size: "",
  city_uf: "",
  cnae_code: 0,
  cnae_description: "",
  company_name: "",
  creation_date: "",
  emails: [
    {
      email: "",
      priority: 0,
    },
  ],
  employee_count: "",
  estimated_revenue: "",
  headquarter_type: "",
  juridical_type: "",
  juridical_type_id: 0,
  land_lines: [],
  legal_representative: [],
  mobile_phones: [
    {
      ddd: 0,
      number: "",
      priority: 0,
      cdr_datetime: null,
      hot_datetime: null,
      whatsapp_datetime: null,
      cpc_datetime: null,
      devices_connected: null,
      active_nao_me_ligue: null,
    },
  ],
  registry_situation: "",
  related_companies: [],
  related_company_members: [],
  related_emails: [],
  related_persons: [
    {
      cpf: 0,
      name: "",
      priority: 0,
      description: "",
      ownership: 0,
      partner: "",
      share: "",
      qualification: "",
    },
  ],
  segment: "",
  share_capital: "",
  simple_simei: {
    status_simei: "",
    dt_option_simei: "",
    status_simple: "",
    dt_option_simple: "",
  },
  trading_name: "",
  ip: "",
};
