export const person = {
  cpf: 0,
  addresses: [
    {
      type: "",
      street: "",
      number: "",
      complement: "",
      neighborhood: "",
      city: "",
      district: "",
      postal_code: "",
      priority: 0,
    },
  ],
  age: "",
  birthday: "",
  bolsa_familia: false,
  cbo_code: "",
  cbo_description: "",
  emails: [
    {
      email: "",
      priority: 0,
    },
  ],
  employer: [],
  estimated_income: "",
  family_persons: [],
  gender: "",
  land_lines: [
    {
      ddd: 0,
      number: "",
      priority: 0,
      cdr_datetime: "",
      hot_datetime: "",
      cpc_datetime: "",
    },
  ],
  mobile_phones: [
    {
      ddd: 0,
      number: "",
      priority: 0,
      cdr_datetime: "",
      hot_datetime: "",
      whatsapp_datetime: "",
      cpc_datetime: "",
      devices_connected: "",
      active_nao_me_ligue: "",
    },
  ],
  mother_name: "",
  name: "",
  pep: false,
  pep_type: "",
  possibly_dead: false,
  registry_situation: "",
  related_companies: [
    {
      cnpj: 0,
      trading_name: "",
      company_name: "",
      registry_situation: "",
      description: "",
      ownership: 0,
    },
  ],
  retired: false,
  rg: "",
  sign: "",
  ip: "",
};
