export const AREAS_DATA = {
  Saúde: {
    Profissões: {
      Médico: ['Endocrinologista', 'Pediatra', 'Ginecologista', 'Obstetra', 'Cardiologista', 'Neurologista', 'Ortopedista', 'Dermatologista', 'Psiquiatra', 'Oftalmologista', 'Otorrinolaringologista', 'Urologista', 'Gastroenterologista', 'Oncologista', 'Reumatologista'],
      Enfermeiro: ['UTI', 'Pediatria', 'Clínica Geral', 'Cirurgia', 'Emergência', 'Ginecologia e Obstetrícia', 'Oncologia', 'Cardiologia', 'Neurologia', 'Pediatria Neonatal'],
      Fisioterapeuta: ['Ortopedia', 'Neurologia', 'Cardiorrespiratória', 'Pediatria', 'Geriatria', 'Dermatofuncional', 'Pilates', 'Acupuntura', 'Reabilitação', 'Esportiva'],
      Nutricionista: ['Esportiva', 'Clínica', 'Comportamental', 'Pediátrica', 'Geriátrica', 'Oncológica', 'Hospitalar', 'Saúde Coletiva', 'Nutrição Funcional', 'Nutrição Estética'],
      Psicólogo: ['Clínico', 'Educacional', 'Organizacional', 'Esportivo', 'Neuropsicologia', 'Psicologia Hospitalar', 'Psicologia da Saúde', 'Psicologia Social', 'Psicologia do Trânsito', 'Psicologia Forense'],
    },
  },
  Tecnologia: {
    Profissões: {
      'Desenvolvedor Frontend': ['React', 'Vue.js', 'Angular', 'Svelte', 'Ember.js', 'Backbone.js', 'jQuery', 'Bootstrap', 'Tailwind CSS', 'Materialize CSS', 'Bulma', 'Foundation', 'Semantic UI', 'Ant Design', 'Chakra UI', 'Styled Components', 'Emotion', 'CSS-in-JS', 'PostCSS', 'Sass', 'Less', 'CSS Modules', 'BEM', 'OOCSS', 'SMACSS', 'Atomic CSS', 'Responsive Design', 'Mobile-First Design', 'Progressive Enhancement', 'Graceful Degradation'],
      'Desenvolvedor Backend': ['Node.js', 'Python', 'Java', 'Ruby', 'PHP', 'C#', 'Go', 'Rust', 'Swift', 'Kotlin', 'Dart', 'Scala', 'Elixir', 'Clojure', 'Haskell', 'TypeScript', 'GraphQL', 'Firebase', 'Serverless', 'Microservices', 'GraphQL', 'RESTful APIs', 'WebSockets', 'GraphQL Subscriptions', 'WebAssembly', 'Progressive Web Apps (PWA)', 'Single Page Applications (SPA)', 'Server-Side Rendering (SSR)', 'Static Site Generation (SSG)'],
      'Desenvolvedor Fullstack': ['MERN Stack', 'MEAN Stack'],
      'DevOps Engineer': ['AWS', 'Docker', 'CI/CD'],
      'QA Engineer': ['Testes Manuais', 'Testes Automatizados'],
      'Data Scientist': ['Machine Learning', 'Deep Learning'],
      'Analista de Dados': ['Power BI', 'Tableau', 'Excel Avançado'],
    },
  },
};
